name: bisulphite-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.6
  - ipykernel
  - pandas
  - numpy
  - bismark
  - fastqc
  - trim-galore
  - multiqc
  - fastq-screen
  - picard
  - pip
  - samtools
  - pip:
    - biopython
